### ISSUE TITLE
Worse performance on Firefox

### ISSUE THREAD

**Issue by Balearica** [scribeocr/scribeocr#11]
Performance is significantly worse on Firefox.  This appears to be, at least in part, due to Fabric.js (the framework we use for drawing the canvas) running significantly slower.   This can be seen by running the benchmark code below in different browsers (for reference, I got 148ms/164ms on Chrome and 585ms/898ms on Firefox, both on Windows 10).  Given that Firefox appears to be the only browser with slower performance and that the issue is not directly caused by this project, I don't think there is much actionable here.  Firefox users with slow performance should consider switching to another browser though. 

https://jsfiddle.net/qtwru8fc/

Also pasting the JavaScript below in case anything happens to jsfiddle. 

```
canvas = new fabric.Canvas('c');
ctx = canvas.getContext('2d');
canvas.renderOnAddRemove = false;

function quantile(arr, ntile){
  if(arr.length == 0){
    return null;
  }
  let arr1 = [...arr];
  const mid = Math.floor(arr.length * ntile)
  arr1.sort((a, b) => a - b);

  return arr1[mid];
}

let time1, time2;
let runs = 50;

let sens1 = [];
let sens2 = [];

for(let r=0;r<runs;r++){
	canvas.clear();
  time1 = Date.now();
  for(let i=0;i<50;i++) {
	for(let j=0;j<20;j++) {

	const textbox = new fabric.IText("abc123", { left: j * 30,
            top: i * 20,
            fontSize: 8,
  });
  canvas.add(textbox);
  }
}

canvas.renderAll();
time2 = Date.now();

if(r >= 10){
	sens1.push(time2 - time1);
}
}

console.log(quantile(sens1, 0.5))

for(let r=0;r<runs;r++){
	canvas.clear();
  time1 = Date.now();
  for(let i=0;i<50;i++) {
	for(let j=0;j<20;j++) {

	const textbox = new fabric.IText("abc123", { left: j * 30,
            top: i * 20,
            fontSize: 8,
            charSpacing: 30
  });
  canvas.add(textbox);
  }
}

canvas.renderAll();
time2 = Date.now();

if(r >= 10){
	sens2.push(time2 - time1);
}
}

console.log(quantile(sens2, 0.5))


```

**Comment by JoanSz** [comment]
I'm using Manjaro/Linux & Firefox and the only big annoyance I'm having is that I cannot resize the window where the recognized stuff appears, making edition of the document a real pain.

**Comment by Balearica** [comment]
@JoanSz It should be possible to zoom by holding control and using the mouse wheel, similar to Microsoft Word, Adobe Acrobat, etc.  I will look into whether it's possible to also add `control` + `+`/`-` as keyboard shortcuts.

**Comment by JoanSz** [comment]
The ctrl+mouse wheel combination works partially. The contents get zoomed
but they are not perfectly centered, which is no big deal in this case.
Now, the problem is that when the image get bigger than the limits of the
window, no scroll bars appear in order to reach all image areas.

Missatge de Balearica ***@***.***> del dia dl., 15 d’abr.
2024 a les 20:34:

**Comment by Balearica** [comment]
When zooming by holding control and moving the mouse wheel, the zoom centers on the position of the cursor.  This will be centered if the cursor if over the center of the document, but can also be used to zoom to a specific region of the document.

Once zoomed in, you can move up/down by scrolling with the mouse wheel, or pan in all directions using the middle mouse button.

**Comment by JoanSz** [comment]
ok, a bit cumbersome if you're not accustomed to, but it definitely works.
Thank you very much.

Missatge de Balearica ***@***.***> del dia dl., 15 d’abr.
2024 a les 23:06:

**Comment by Balearica** [comment]
I added `control` + `+`/`-` as keyboard shortcuts for zoom.

**Comment by Balearica** [comment]
Closing as resolved.  The Fabric.js dependency that motivated this issue has been removed.  Additionally, Opentype.js was also slower on Firefox, however this has since been patched.  Firefox is now slightly slower than on Chrome, however this is normal, and the difference is not extreme like it was before.
