### ISSUE TITLE
Tesseract Misidentifies Font Metrics (Line Height, Ascender, Descender)

### ISSUE THREAD

**Issue by Balearica** [scribeocr/scribeocr#17]
Tesseract frequently misidentifies text size.  The error can be in either direction--either too small or too large.  It appears to only happen when a line does not contain both ascenders and descenders, but does not happen in all such cases.  An example that contains both a line misidentified as too large and a line misidentified as too small is below. 

![font_size_example](https://user-images.githubusercontent.com/100809261/171339201-f3742366-e17c-43fd-b757-2f650decb83f.PNG)
 
The original image is [here](https://user-images.githubusercontent.com/100809261/171338732-009385ce-30f8-439d-a16c-1ba868ecee21.png).

**Comment by Balearica** [comment]
The ultimate cause of this phenomenon appears to be that font size is estimated on the line-level _before_ recognizing text content, and never re-calculated the text is known. 

https://github.com/tesseract-ocr/tesseract/blob/60fd2b4abaa9c5c5c42d32db57576bc95d28a78a/src/textord/makerow.cpp

**Comment by JoanSz** [comment]
Yeah, I can confirm that in every test I've been performing. What a pity.

**Comment by Balearica** [comment]
Closing as resolved.  As noted above, positioning has been significantly improved and now works correctly for the original example. 

Please open a new issue with reproducible examples if you find positioning is broken in a systematic way with a class of documents (i.e. beyond one-off errors).
