### ISSUE TITLE
Support pasting image from clipboard

### ISSUE THREAD

**Issue by rugk** [scribeocr/scribeocr#22]
## User story

I as an end user would like to paste an image I copied from social media, because I cannot read the text, because it is in another language and so I want to extract the text and copy it in a translator tool.

That is actually the true story how I ended up here. More back story: https://github.com/naptha/tesseract.js/issues/768#issuecomment-1688658777#

Same as in #23

## Solution

It was hard enough to find it, saving the file and uploading is again inconvenient. I would love if you could just copy/paste it.

If it helps, here is an example PR (that is likely not so clean aka old and introduced much more)… https://github.com/PrivateBin/PrivateBin/pull/182

**Comment by Balearica** [comment]
The site has been updated to support uploading individual images by copy/pasting them from the clipboard.
