### ISSUE TITLE
Support drag and drop for images in other sites

### ISSUE THREAD

**Issue by rugk** [scribeocr/scribeocr#23]
## User story

I as an end user would like to paste an image I copied from social media, because I cannot read the text, because it is in another language and so I want to extract the text and copy it in a translator tool.

That is actually the true story how I ended up here. More back story: https://github.com/naptha/tesseract.js/issues/768#issuecomment-1688658777

same as in https://github.com/scribeocr/scribeocr/issues/22

## Solution

It was hard enough to find it, saving the file and uploading is again inconvenient. I would love if you could just drag and drop the file from social media or e.g. a saved file to upload it. Just another UX thing.

If it helps, here is an example PR (that is likely not so clean aka old and introduced much more)… https://github.com/PrivateBin/PrivateBin/pull/182

**Comment by Balearica** [comment]
I think this is a good UX suggestion so will add to the site.  However, I think the bigger issue for your use-case is that there needs to be an option for selecting what language to recognize the text as.  Neither should be particularly hard to implement, so I will add.

**Comment by rugk** [comment]
Same, but yeah would be a good different issue extracted from the use case/user story, did not even think about it ("automatic" was fine for me I guess).

**Comment by Balearica** [comment]
Closing as completed.  You can now drag and drop images from other websites.
