### ISSUE TITLE
Support for non-English text-recognition languages?

### ISSUE THREAD

**Issue by brlin-tw** [scribeocr/scribeocr#26]
It seems that currently only English text is supported:

![Screenshot](https://github.com/scribeocr/scribeocr/assets/13408130/7f948cc4-c098-42a1-9fae-9ab5a35f82ed)

Are there any plans to support other text-recognition languages?

**Comment by JoanSz** [comment]
I suppose that a local app (a project which I'm already aware of) would use the local installation of tesseract, which would solve the language issue, at least in the terms you stated, i.e., mainly for other latin script-based languages. I'm interested in using catalan, btw.

By now, I'll try to play with hocr files from ocrmypdf in order to edit them using scribeocr (if I manage how to do it). Again, a local app could also benefit from spelling check features. Regards.

**Comment by Balearica** [comment]
@JoanSz I added support for Catalan.  

In general, it is easy to add any language that uses the Latin alphabet and is supported by Tesseract/Tesseract.js.  Languages that use non-Latin scripts are more difficult.

**Comment by JoanSz** [comment]
Ok, thank you very much!!!

**Comment by JoanSz** [comment]
So, to use the catalan OCR I need to update, or clone and reinstall? (Sorry, I'm kind of newbie in github)

**Comment by Balearica** [comment]
@JoanSz The latest version is always live at [scribeocr.com](https://scribeocr.com/).  In general, I am not aware of any advantages to serving the site on your local network if you are not a developer making changes to the repo, so if you are simply looking to use the application, I would lean towards using the public site. 

Alternatively, if you already cloned yourself and are running an HTTP server on your local network, you would need to run `git pull` from within this repo to update to the latest version.  You could also just clone from scratch using the instructions in the [readme](https://github.com/scribeocr/scribeocr?tab=readme-ov-file#running).

**Comment by guidiasz** [comment]
Could you add support for Portuguese?

**Comment by yespah** [comment]
Could you add support for danish? The danish letters æ, ø and å always needs to be corrected.

**Comment by Balearica** [comment]
@yespah Sure, I added Danish.

**Comment by conceptualGabrielPutnam** [comment]
Hi, attempting to OCR the Etymologiae [1] of Isidore_of_Seville [2] found at Internet Archive [3] made by user ruth_worboys with a copy from the Boston Public Library scan of the 1483 publishing by Venitian publisher Peter Loslein to try and have a faithful translation to English with limited author based bias or interpretation of old literature based on several different translation tool attempts from direct Latin.

However...one of the main issues, other than being a 280 page document in dense text, is that the entire document is in old Latin, used Latin script writing, and features a large number of Latin specific script letters [4], and obviously is entirely in old Latin words.

Primary Request: Could Latin-script letters be added so those at least get recognized correctly?

Secondary: Could an old Latin dictionary for word recognition be added?

Also, found this project a couple months ago and totally amazed at being able to do high quality OCR in the browser on PDFs.  Incredibly for gaming literature to text format and similar projects.  One of the only OCR that even recognizes number heavy tables correctly.  Thanks much for the excellent work.  Realize the request is not a "light" request.

  [1] https://en.wikipedia.org/wiki/Etymologiae
  [2] https://en.wikipedia.org/wiki/Isidore_of_Seville
  [3] https://archive.org/details/etymologiaeaddde00isid
  [4] https://en.wikipedia.org/wiki/List_of_Latin-script_letters

Gabriel Putnam

**Comment by Balearica** [comment]
@conceptualGabrielPutnam Can you paste this comment into a new Git Issue specific to Latin?  I will think about this and respond there.  While everybody has been using this one, different languages do have different implementation challenges and I want to avoid sending out email alerts to users interested only in other languages.

**Comment by Balearica** [comment]
Closing this issue to avoid overly-broad discussion about every language.  If you would like to request support for a new language, please make a new Git Issue specific to that language.
