### ISSUE TITLE
Seven Segment text recognition problem

### ISSUE THREAD

**Issue by tekbuds** [scribeocr/scribeocr#27]
![dr-morphen-5](https://github.com/scribeocr/scribeocr/assets/13183070/a1dafc1b-1441-407e-a68d-5cb2c665def9)

I am trying to recognize numbers 120 and 80 from this image. But this is not recognizing that. Any idea why and is there a way to fix it?

**Comment by Balearica** [comment]
I was similarly unable to recognize these numbers.  Unfortunately, I don't think patching to make this type of recognition work is possible.  Therefore, as this is outside of the core use-case of this application (documents, books, etc.) I am closing this issue. 

For context, ScribeOCR uses a fork of Tesseract, and recognizing sparse text comprised of non-continuous line segments simply violates too many assumptions that Tesseract makes for Tesseract to be the correct tool here.  Furthermore, even if it could be recognized correctly, ScribeOCR would not be able to represent/overlay the text precisely (the primary value-add of ScribeOCR) as it does not contain a similar font.
