### ISSUE TITLE
Loading Existing OCR Data (.hocr) fails

### ISSUE THREAD

**Issue by dev1978** [scribeocr/scribeocr#35]
Unfortunately scribeOCR seems to have changed .hocr processing in the last two weeks. I can't import/load my PDF with the .hocr -file anymore. Importing the Image containing PDF works. But not with the .hocr -file. Machine and browser setup hasn't changed here. If I upload my .hocr -file trough the Evaluate/Upload function the already proofread text is misplaced to the top and left. Font sizing is also wrong. Baseline is screwed.
Is there any fix I could try?  I transcribed/edited almost 70 pages of an old manuscript. And I would really regret to have wasted a week of work.

**Comment by Balearica** [comment]
That definitely should not happen, my apologies.  I will look into this later today and let you know if I need any more information.

**Comment by Balearica** [comment]
@dev1978 I loaded several `.hocr` files I had on hand from older versions of ScribeOCR, and found that there were indeed issues loading the files.  I implemented several patches to restore compatibility with `.hocr` created in earlier versions.  Please let me know if this resolved your issues.

Process-wise, I think the core issue was that we need automated tests that ensure backwards compatibility with the `.hocr` files generated with previous versions of Scribe OCR.  Automated tests already exist for `.hocr` in general (using data from Tesseract), however there are aspects of `.hocr` imports unique to restoring previous Scribe OCR sessions that need to be tested.

**Comment by Balearica** [comment]
One additional note: starting in April 2024, on the 28th of every month a snapshot of the repo is created and hosted on a subdomain.  These are found at `[year-month].scribeocr.com`.  For example, the snapshot from May 28th can be found at [2024-05.scribeocr.com](https://2024-05.scribeocr.com).  These are intended to be used in a pinch in case some new update breaks something--not relied on long-term.  Anybody who uses a snapshot version due to an issue in the current version should be sure to report the bug so it can be patched.

**Comment by dev1978** [comment]
You are the unknown hero of my day. Thank you so much! Everything fits again perfect.

Your comment on how to access a snapshoted version is helpful and trust building! Maybe your team decides to add it on the faq page. 

Thank you again. And have a great day! 🙂

**Comment by Balearica** [comment]
Glad this could be resolved.  Thanks for the suggestion, I added a new "Support" page in the docs, with a section explaining how to use snapshots of earlier versions.

https://docs.scribeocr.com/support.html#using-older-versions
