### ISSUE TITLE
Add support for bold fonts

### ISSUE THREAD

**Issue by Balearica** [scribeocr/scribeocr#38]
Bold fonts are currently not supported because we cannot accurately identify bold words during OCR and font detection in the same way that we can identify italic words.  However, this is still worth adding, as (1) users can set fonts to bold manually and (2) when extracting native text from documents, we know for a fact what text is bold.

**Comment by 99bits** [comment]
That's a great feature and the fact that ScribeOcr is able to replicate fonts is amazing.  
Can you give more detailed information where in the code is ScribeOcr is doing the font detection.

**Comment by Balearica** [comment]
Closing as completed as this feature was added about a month ago.  Font detection in general can be discussed in the discussion #52.
