### ISSUE TITLE
Is there an option to switch Ligatures On/Off 

### ISSUE THREAD

**Issue by dev1978** [scribeocr/scribeocr#49]
Hello there,
I wonder if there is an option to use, or not-use [ligatures]( https://en.wikipedia.org/wiki/Ligature_(writing))? 

Attached example: The original typewriter did not use ligatures but the chosen «century» font in scribeOCR uses them automatically for the character ff  makes a narrow version out of it. 

Example (Original with scribeOCR overlay) : 
<img width="198" alt="Bildschirmfoto 2024-07-13 um 00 40 44" src="https://github.com/user-attachments/assets/c7f5baaa-99d2-4610-8c13-42a9f0e07dc9">

**Comment by Balearica** [comment]
There is currently no option for this.  I agree it should be added, given that many documents use ligatures, many do not, and this has a significant impact on how accurate text overlays are.  I don't think this is particularly hard to implement, so will try and add an option in the near future.

**Comment by Balearica** [comment]
I added an option for this under `Edit` -> `Options` -> `Ligatures`.

![ligature_option](https://github.com/user-attachments/assets/bc8aa4fa-091f-42c7-8a87-55b6b8b7943b)

**Comment by dev1978** [comment]
Fantastic! What a support. – I luv u 💋︎
