### ISSUE TITLE
Cursor position resets on edit

### ISSUE THREAD

**Issue by neolev** [scribeocr/scribeocr#55]
Starting from commit aea402942003e3d13cf38c37830e7434add4d852, I noticed the cursor moves to the start of the word when key is pressed. 

Added a pull request here https://github.com/scribeocr/scribeocr/pull/54 to fix that.

**Comment by Balearica** [comment]
Can you provide more detail on the conditions under which this occurs?  What browser/device are you using?  What key press is causing the cursor to move to the start of the word (simply adding letters)?  I have not noticed this happening on Chrome at all, so am guessing this happens under more narrow conditions.

**Comment by neolev** [comment]
I've encountered this on Firefox 128.0.3 on Linux, so maybe it happens there only since I haven't tried other browsers. The issue occurs after running `Recognize Text` and trying to edit the low confidence text, for example if the low confidence word is `foo` and the edit is to `food` then the text cursor will jump back behind the first letter `f`. After seeing this I tried git bisect until the issue disappeared, every time I made sure to clear browser cache and re-install the `npm` packages before re-running the server.

**Comment by Balearica** [comment]
Thanks.  I was able to replicate this on Firefox.  It looks like there are browser-specific differences regarding what triggers the `input` event, which results in this bug only happening on certain browsers.  Will merge the fix you implemented in #54.

**Comment by neolev** [comment]
Looks like it was such an edge case, thanks for sorting this. Cheers.
